"use client";

import { useState, useEffect, useMemo } from "react";
import Link from "next/link";
import { getSites, type ExplorationSite, type RiskBand } from "@/src/services/siteService";

type PriorityListStatus = "DRAFT" | "SUBMITTED_FOR_REVIEW" | "APPROVED" | "REJECTED";

export default function SeniorDecisionsPage() {
  const [sites, setSites] = useState<ExplorationSite[]>([]);
  const [listStatus, setListStatus] = useState<PriorityListStatus>("SUBMITTED_FOR_REVIEW");
  const [reviewComment, setReviewComment] = useState("");
  const [saved, setSaved] = useState(false);
  const [userRole, setUserRole] = useState("senior_officer");
  
  // Tab states
  const [activeTab, setActiveTab] = useState<"prioritized" | "recommendations" | "dashboard">("prioritized");

  // Search/Filters/Sorting State
  const [search, setSearch] = useState("");
  const [districtFilter, setDistrictFilter] = useState("");
  const [riskFilter, setRiskFilter] = useState("");
  
  // Selected site modal
  const [selectedSite, setSelectedSite] = useState<ExplorationSite | null>(null);

  useEffect(() => {
    // Read user role from localStorage
    if (typeof window !== "undefined") {
      const role = window.localStorage.getItem("user_role") ?? "senior_officer";
      setUserRole(role);
      
      const savedStatus = window.localStorage.getItem("conservation_priority_status") as PriorityListStatus;
      if (savedStatus) {
        setListStatus(savedStatus);
      }
      
      const savedComment = window.localStorage.getItem("conservation_priority_comment");
      if (savedComment) {
        setReviewComment(savedComment);
      }
    }
    
    // Only display APPROVED sites for conservation prioritization
    const approvedSites = getSites().filter(s => s.status === "APPROVED");
    setSites(approvedSites);
  }, []);

  const sortedSites = useMemo(() => {
    // Rank by AI Risk Score descending
    const result = [...sites].sort((a, b) => (b.riskScore ?? 0) - (a.riskScore ?? 0));
    return result;
  }, [sites]);

  const filteredSites = useMemo(() => {
    return sortedSites.filter(s => {
      if (districtFilter && s.district !== districtFilter) return false;
      if (riskFilter && s.riskBand !== riskFilter) return false;
      if (search.trim() && !s.name.toLowerCase().includes(search.toLowerCase().trim())) return false;
      return true;
    });
  }, [sortedSites, search, districtFilter, riskFilter]);

  const districts = useMemo(() => {
    return Array.from(new Set(sites.map(s => s.district)));
  }, [sites]);

  function handleStatusUpdate(newStatus: PriorityListStatus) {
    if (userRole === "analyst") {
      alert("Analysts can generate prioritizations but cannot give final approval decisions.");
      return;
    }
    setListStatus(newStatus);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("conservation_priority_status", newStatus);
      window.localStorage.setItem("conservation_priority_comment", reviewComment);
    }
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  }

  function handleSaveDraftList() {
    if (typeof window !== "undefined") {
      window.localStorage.setItem("conservation_priority_status", "DRAFT");
      setListStatus("DRAFT");
    }
    alert("Priority list successfully saved to local drafts.");
  }

  return (
    <div className="flex flex-1 flex-col">
      <header className="flex items-center justify-between border-b border-[#DEDBD1] bg-[#FAF6EB] px-8 py-4">
        <div>
          <h1 className="font-serif text-[20px] tracking-tight text-[#3A2A12]">Decision Support Board</h1>
          <p className="mt-0.5 text-[12.5px] text-[#8A8478]">
            Vulnerability-ranked priority prioritization and authorization of active conservation lists.
          </p>
        </div>
      </header>

      <main className="flex-1 px-8 py-7 bg-[#F0E6C8]/30">
        
        {/* Status Alert & Decision Control Row */}
        <div className="mb-6 rounded-[8px] border border-[#DEDBD1] bg-white p-5 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <span className="block text-[11px] font-bold text-[#8A8D86] uppercase">Conservation Prioritization Status</span>
            <div className="flex items-center gap-2 mt-1">
              <StatusBadge status={listStatus} />
              <span className="text-[12.5px] text-[#5B6472]">
                {listStatus === "SUBMITTED_FOR_REVIEW" && "Awaiting Senior Officer review & sign-off"}
                {listStatus === "APPROVED" && "Priorities authorized and added to national archive"}
                {listStatus === "REJECTED" && "Revision requested by Senior Officer"}
                {listStatus === "DRAFT" && "Draft generated by GIS Analyst"}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {userRole !== "analyst" ? (
              <>
                <button
                  onClick={() => handleStatusUpdate("APPROVED")}
                  disabled={listStatus === "APPROVED"}
                  className="rounded-[6px] bg-[#2C6B33] px-4 py-2 text-[12.5px] font-medium text-[#F4F2ED] hover:bg-[#1E4D23] transition disabled:opacity-50"
                >
                  Authorize Priorities
                </button>
                <button
                  onClick={() => handleStatusUpdate("REJECTED")}
                  disabled={listStatus === "REJECTED"}
                  className="rounded-[6px] bg-[#B03A2E] px-4 py-2 text-[12.5px] font-medium text-[#F4F2ED] hover:bg-[#8A2E25] transition disabled:opacity-50"
                >
                  Request revision
                </button>
              </>
            ) : (
              <>
                <button
                  onClick={handleSaveDraftList}
                  className="rounded-[6px] border border-[#D4CFC3] bg-white px-4 py-2 text-[12.5px] font-medium text-[#5B6472] hover:bg-[#FAF6EB]"
                >
                  Save Priority Draft
                </button>
                <button
                  onClick={() => handleStatusUpdate("SUBMITTED_FOR_REVIEW")}
                  disabled={listStatus === "SUBMITTED_FOR_REVIEW"}
                  className="rounded-[6px] bg-[#BB892C] px-4 py-2 text-[12.5px] font-medium text-[#F4F2ED] hover:bg-[#8F6A21]"
                >
                  Submit for Approval
                </button>
              </>
            )}
            {saved && <span className="text-[12.5px] text-[#2C6B33] font-medium">Status Updated!</span>}
          </div>
        </div>

        {/* Comment field for approval review */}
        {userRole !== "analyst" && listStatus === "SUBMITTED_FOR_REVIEW" && (
          <div className="mb-5 bg-white border border-[#DEDBD1] rounded-[8px] p-4.5">
            <label htmlFor="priorityComments" className="block text-[12px] font-bold text-[#3A2A12] uppercase mb-1">
              Review remarks
            </label>
            <input
              id="priorityComments"
              type="text"
              value={reviewComment}
              onChange={(e) => setReviewComment(e.target.value)}
              placeholder="Add verification signatures or comments regarding priority order adjustments..."
              className="w-full rounded-[6px] border border-[#D4CFC3] px-3.5 py-2 text-[13px] outline-none"
            />
          </div>
        )}

        {/* Navigation Tabs */}
        <div className="flex gap-1.5 border-b border-[#DEDBD1]">
          <button
            type="button"
            onClick={() => setActiveTab("prioritized")}
            className={`px-4 py-2.5 text-[13px] font-medium transition ${
              activeTab === "prioritized" ? "border-b-2 border-[#BB892C] text-[#BB892C] font-semibold" : "text-[#8A8D86] hover:text-[#5B6472]"
            }`}
          >
            Vulnerability Ranked sites
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("recommendations")}
            className={`px-4 py-2.5 text-[13px] font-medium transition ${
              activeTab === "recommendations" ? "border-b-2 border-[#BB892C] text-[#BB892C] font-semibold" : "text-[#8A8D86] hover:text-[#5B6472]"
            }`}
          >
            Conservation Recommendations
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("dashboard")}
            className={`px-4 py-2.5 text-[13px] font-medium transition ${
              activeTab === "dashboard" ? "border-b-2 border-[#BB892C] text-[#BB892C] font-semibold" : "text-[#8A8D86] hover:text-[#5B6472]"
            }`}
          >
            Risk Dashboard Analytics
          </button>
        </div>

        {/* Search, Filter Controls */}
        {activeTab !== "dashboard" && (
          <div className="mt-5 mb-5 flex flex-wrap items-center justify-between gap-3 rounded-[8px] border border-[#DEDBD1] bg-white p-4">
            <input
              type="text"
              placeholder="Search site name…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full max-w-sm rounded-[6px] border border-[#D4CFC3] px-3.5 py-1.5 text-[13px] outline-none"
            />

            <div className="flex gap-2">
              <select
                value={districtFilter}
                onChange={(e) => setDistrictFilter(e.target.value)}
                className="rounded-[6px] border border-[#D4CFC3] bg-white px-3 py-1.5 text-[13px] outline-none text-[#5B6472]"
              >
                <option value="">All Districts</option>
                {districts.map(d => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>

              <select
                value={riskFilter}
                onChange={(e) => setRiskFilter(e.target.value)}
                className="rounded-[6px] border border-[#D4CFC3] bg-white px-3 py-1.5 text-[13px] outline-none text-[#5B6472]"
              >
                <option value="">All Risks</option>
                <option value="VERY_HIGH">Very High</option>
                <option value="HIGH">High</option>
                <option value="MODERATE">Moderate</option>
                <option value="LOW">Low</option>
              </select>
            </div>
          </div>
        )}

        {/* Tab content rendering */}
        <div className="mt-5">
          {activeTab === "prioritized" && (
            <div className="overflow-hidden rounded-[8px] border border-[#DEDBD1] bg-white shadow-xs">
              <table className="w-full text-left text-[13px]">
                <thead>
                  <tr className="bg-[#3A2A12] text-[#F4F2ED]">
                    <th className="px-5 py-3 font-medium">Rank</th>
                    <th className="px-5 py-3 font-medium">Site name</th>
                    <th className="px-5 py-3 font-medium">District</th>
                    <th className="px-5 py-3 font-medium">Vulnerability score</th>
                    <th className="px-5 py-3 font-medium">Risk Band</th>
                    <th className="px-5 py-3 font-medium text-right">Details</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#DEDBD1]/60">
                  {filteredSites.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-5 py-6 text-center text-[#8A8D86]">
                        No approved sites available to prioritize.
                      </td>
                    </tr>
                  ) : (
                    filteredSites.map((site, i) => (
                      <tr
                        key={site.id}
                        onClick={() => setSelectedSite(site)}
                        className={`hover:bg-[#FAF6EB]/40 cursor-pointer transition-colors ${
                          i % 2 === 1 ? "bg-[#FAF6EB]/20" : ""
                        }`}
                      >
                        <td className="px-5 py-3 font-serif font-bold text-[#BB892C]">#{i + 1}</td>
                        <td className="px-5 py-3 font-semibold text-[#3A2A12]">{site.name}</td>
                        <td className="px-5 py-3 text-[#5B6472]">{site.district}</td>
                        <td className="px-5 py-3 font-bold text-[#BB892C]">{site.riskScore}%</td>
                        <td className="px-5 py-3">
                          <RiskBandBadge band={site.riskBand!} />
                        </td>
                        <td className="px-5 py-3 text-right" onClick={(e) => e.stopPropagation()}>
                          <button
                            type="button"
                            onClick={() => setSelectedSite(site)}
                            className="text-[13px] font-semibold text-[#BB892C] hover:underline"
                          >
                            Details
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          )}

          {activeTab === "recommendations" && (
            <div className="space-y-4">
              {filteredSites.map((site) => {
                let rec = "Schedule structural checks and reinforce retaining wall masonry joints.";
                if (site.floodZone === "High") rec = "Construct diversion pathways to shield historic stone bases from flash floods.";
                else if (site.lootingHistory === "Yes") rec = "Install remote solar security cameras and schedule bi-weekly military security checks.";
                else if (site.encroachment === "High") rec = "Demarcate strict physical boundaries and restrict development within 500m.";

                return (
                  <div key={site.id} className="rounded-[8px] border border-[#DEDBD1] bg-white p-5 shadow-xs flex items-start gap-4">
                    <span className="text-[20px] font-serif font-bold text-[#BB892C] mt-1">#</span>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <h4 className="font-serif text-[15px] font-bold text-[#3A2A12]">{site.name}</h4>
                        <RiskBandBadge band={site.riskBand!} />
                      </div>
                      <p className="mt-2 text-[13px] leading-relaxed text-[#5B6472]">
                        <span className="font-bold text-[#BB892C]">Conservation action:</span> {rec}
                      </p>
                      <p className="mt-1 text-[11px] text-[#8A8D86]">Contributing attributes: Flood vulnerability ({site.floodZone}), looting history ({site.lootingHistory}), significance rank ({site.significance}/10).</p>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {activeTab === "dashboard" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Risk Band Counts */}
              <div className="rounded-[8px] border border-[#DEDBD1] bg-white p-5 shadow-xs">
                <h3 className="font-serif text-[15px] text-[#3A2A12] border-b border-[#DEDBD1]/60 pb-2 mb-4">Risk bands Distribution</h3>
                <div className="space-y-4">
                  <DashboardRow label="Very High Risk (76-100%)" count={sites.filter(s => s.riskBand === "VERY_HIGH").length} color="#B03A2E" total={sites.length} />
                  <DashboardRow label="High Risk (51-75%)" count={sites.filter(s => s.riskBand === "HIGH").length} color="#9A5A2E" total={sites.length} />
                  <DashboardRow label="Moderate Risk (26-50%)" count={sites.filter(s => s.riskBand === "MODERATE").length} color="#BB892C" total={sites.length} />
                  <DashboardRow label="Low Risk (0-25%)" count={sites.filter(s => s.riskBand === "LOW").length} color="#2C6B33" total={sites.length} />
                </div>
              </div>

              {/* General Insights */}
              <div className="rounded-[8px] border border-[#DEDBD1] bg-white p-5 shadow-xs space-y-4">
                <h3 className="font-serif text-[15px] text-[#3A2A12] border-b border-[#DEDBD1]/60 pb-2">Vulnerability Insights</h3>
                <div className="text-[12.5px] text-[#5B6472] space-y-3 leading-relaxed">
                  <p>
                    <span className="font-bold text-[#3A2A12]">Critical sectors:</span> 
                    {" "}Based on dynamic AI prediction mappings, Anuradhapura and Matale districts display the highest clustering of &quot;Very High&quot; and &quot;High&quot; risk sites due to urban encroachment and low elevation flood-risk.
                  </p>
                  <p>
                    <span className="font-bold text-[#3A2A12]">Conservation urgency:</span> 
                    {" "}Retaining walls and masonry bases display severe vulnerabilities when exposed to rainfall indices exceeding 1,800 mm/year combined with medium soil erosion ratings.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* ---------------- SITE DETAILS MODAL ---------------- */}
      {selectedSite && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs p-4">
          <div className="w-full max-w-lg rounded-[8px] border border-[#DEDBD1] bg-white p-6 shadow-lg">
            <div className="flex items-center justify-between border-b border-[#DEDBD1] pb-3 mb-4">
              <h3 className="font-serif text-[17px] text-[#3A2A12]">{selectedSite.name}</h3>
              <button
                type="button"
                onClick={() => setSelectedSite(null)}
                className="text-[20px] text-[#8A8D86] hover:text-[#3A2A12] leading-none"
              >
                &times;
              </button>
            </div>

            <div className="space-y-4 text-[13px] max-h-[70vh] overflow-y-auto pr-1">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="block text-[11px] text-[#8A8D86] uppercase font-bold">District</span>
                  <span className="text-[#3A4048]">{selectedSite.district}</span>
                </div>
                <div>
                  <span className="block text-[11px] text-[#8A8D86] uppercase font-bold">AI Risk Score</span>
                  <span className="font-bold text-[16px] text-[#BB892C]">{selectedSite.riskScore}% ({selectedSite.riskBand})</span>
                </div>
              </div>

              <div>
                <span className="block text-[11px] text-[#8A8D86] uppercase font-bold mb-1.5">Contributing attributes</span>
                <div className="grid grid-cols-2 gap-2 text-[12px]">
                  <div className="p-2 bg-[#FAF9F6] border border-[#DEDBD1]/30 rounded">
                    <span className="text-[10px] text-[#8A8D86] block">Elevation</span>
                    <span className="font-medium">{selectedSite.elevation}m</span>
                  </div>
                  <div className="p-2 bg-[#FAF9F6] border border-[#DEDBD1]/30 rounded">
                    <span className="text-[10px] text-[#8A8D86] block">Flood zone</span>
                    <span className="font-medium">{selectedSite.floodZone}</span>
                  </div>
                  <div className="p-2 bg-[#FAF9F6] border border-[#DEDBD1]/30 rounded">
                    <span className="text-[10px] text-[#8A8D86] block">Soil erosion</span>
                    <span className="font-medium">{selectedSite.erosionIndex}</span>
                  </div>
                  <div className="p-2 bg-[#FAF9F6] border border-[#DEDBD1]/30 rounded">
                    <span className="text-[10px] text-[#8A8D86] block">River Proximity</span>
                    <span className="font-medium">{selectedSite.distanceToRiver}</span>
                  </div>
                </div>
              </div>

              <div>
                <span className="block text-[11px] text-[#8A8D86] uppercase font-bold">Exploration notes</span>
                <p className="mt-1 text-[#5B6472] italic leading-relaxed bg-[#FAF9F6] p-3 border border-[#DEDBD1]/40 rounded">&ldquo;{selectedSite.notes}&rdquo;</p>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-2 border-t border-[#DEDBD1] pt-3">
              <button
                type="button"
                onClick={() => setSelectedSite(null)}
                className="rounded-[6px] border border-[#DEDBD1] px-4 py-2 text-[13px] text-[#5B6472] hover:bg-[#FAF6EB]"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: PriorityListStatus }) {
  const config: Record<PriorityListStatus, { label: string; bg: string; text: string }> = {
    DRAFT: { label: "Draft list", bg: "#EFEEEA", text: "#5B6472" },
    SUBMITTED_FOR_REVIEW: { label: "Pending validation", bg: "#FBF0EB", text: "#9A5A2E" },
    APPROVED: { label: "Authorized list", bg: "#EAF3EA", text: "#2C6B33" },
    REJECTED: { label: "Needs revision", bg: "#FBEBEA", text: "#B03A2E" },
  };
  const { label, bg, text } = config[status];

  return (
    <span
      className="inline-block rounded-[4px] px-2.5 py-0.5 text-[12px] font-bold border border-black/5"
      style={{ backgroundColor: bg, color: text }}
    >
      {label}
    </span>
  );
}

function RiskBandBadge({ band }: { band: string }) {
  const config: Record<string, string> = {
    VERY_HIGH: "bg-[#F6E0DC] text-[#8A2418] border-[#8A2418]/20",
    HIGH: "bg-[#FBEBEA] text-[#B03A2E] border-[#B03A2E]/20",
    MODERATE: "bg-[#FBF0EB] text-[#9A5A2E] border-[#9A5A2E]/20",
    LOW: "bg-[#EAF3EA] text-[#2C6B33] border-[#2C6B33]/20",
  };
  const style = config[band] || "bg-[#EFEEEA] text-[#5B6472]";
  return (
    <span className={`inline-block rounded px-2.5 py-0.5 text-[11px] font-bold border ${style}`}>
      {band.replace("_", " ")} RISK
    </span>
  );
}

function DashboardRow({ label, count, color, total }: { label: string; count: number; color: string; total: number }) {
  const pct = total > 0 ? Math.round((count / total) * 100) : 0;
  return (
    <div>
      <div className="flex justify-between text-[12.5px] text-[#5B6472]">
        <span>{label}</span>
        <span className="font-bold">{count} sites ({pct}%)</span>
      </div>
      <div className="mt-1 h-2 w-full bg-[#FAF6EB] rounded-full overflow-hidden">
        <div className="h-full rounded-full" style={{ width: `${pct}%`, backgroundColor: color }} />
      </div>
    </div>
  );
}
